<?php echo $this->doctype(); ?>
<html>
	<head>
		<?php echo $this->headMeta();  ?>	  
	    <?php echo $this->headTitle(); ?>
	    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">	    
		<!--[if lt IE 9]>
			<link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/ie.css" type="text/css" media="screen" />
			<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->		
		<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
	    <script type="text/javascript">var baseUrl = "<?php echo $this->baseUrl(); ?>"; </script>
	    <?php $this->headLink()->appendStylesheet($this->baseUrl('//widget/Bootstrap/css/bootstrap.min.css'))
	    					   ->appendStylesheet($this->baseUrl('//widget/Bootstrap/css/bootstrap-responsive.min.css'))
	    					   ->appendStylesheet($this->baseUrl('/widget/JqueryUI/css/jquery-ui-1.10.0.custom-bootstrap.css'))
	    					   ->appendStylesheet($this->baseUrl('/widget/JqueryUI/css/jquery.ui.1.10.0.ie-bootstrap.css'))
	    					   ->appendStylesheet($this->baseUrl('/widget/JqueryUI/css/jquery.ui.multiselect.css'))
	    					   ->appendStylesheet($this->baseUrl('/widget/DataTables/media/css/DT_bootstrap.css')); ?>
	    					   
	    <?php $this->headScript()->appendFile($this->baseUrl('/js/jquery-1.9.0.min.js'))
	    						 ->appendFile($this->baseUrl('/js/jquery.browser.js'))
	    						 ->appendFile($this->baseUrl('/js/main.js'))	    						    						
	    						 ->appendFile($this->baseUrl('/widget/JqueryUI/js/jquery-ui-1.10.0.custom.min.js'))
	    						 ->appendFile($this->baseUrl('/widget/JqueryUI/js/jquery.ui.multiselect.js'))
	    						 ->appendFile($this->baseUrl('/widget/JqueryUI/js/jquery.ui.multiselect-es.js'))
	    						 ->appendFile($this->baseUrl('/widget/JqueryUI/js/jquery.ui.datepicker-es.js'))
	    						 ->appendFile($this->baseUrl('/widget/Globalize/globalize.js'))	    						 
	    						 ->appendFile($this->baseUrl('/widget/Globalize/cultures/globalize.culture.de-DE.js'))
	    						 ->appendFile($this->baseUrl('/widget/Bootstrap/js/bootstrap.min.js'))
	    						 ->appendFile($this->baseUrl('/widget/DataTables/media/js/jquery.dataTables.min.js'))
	    						 ->appendFile($this->baseUrl('/widget/DataTables/media/js/DT_bootstrap.js'))
	    						 ->appendFile($this->baseUrl('/widget/DataTables/extras/ColumnFilter/js/jquery.dataTables.columnFilter.js')); ?>		
	    <?php echo $this->headLink(); ?>
	    <?php echo $this->headScript(); ?>		    	
	</head>
	<body>		
		<?php if(App_User::isLogged()) :?>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container-fluid">		
	    <?php 	echo $this->navigation()->menu(); ?>
			    </div>
			</div>
		</div>		    	
	    <?php endif; ?>		
	    <div class="container" style="padding-top: 90px;">    
	    	<?php echo $this->layout()->content; ?>
	    </div>		   
	</body>
</html>